repos:
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      args:
        - --ignore=E501,E266,W503,F401,F841,E203
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: end-of-file-fixer
